### ISSUE TITLE
Changes for education

### ISSUE THREAD

**Issue by m-vv** [Kottans/Kottans_Web_Game#11]
If our project have educational purpose too I propose:
do this steps of commit
1. make  Feathers application without nothing
2. make it working in Docker
3. add service that can work with MondoDB 
4. add user auth
5. only after that add some frontend
...
All files should have explanation in comment and maybe we can write our own tutorial.
I'm open for ideas how we can make this work more helpful for future learners.

**Comment by lempiy** [comment]
I think that will slow down our work hardly. 
Its only yours training project, I had no sharing purposes when I've started.
Any steps of our work will be saved in commit history.

**Comment by m-vv** [comment]
Maybe you wright, but as we can see we already do refactoring based on Feathers.
