### ISSUE TITLE
Login component &route

### ISSUE THREAD

**Issue by AMashoshyna** [Kottans/Kottans_Web_Game#22]
Create login component and secondary route #

**Comment by AMashoshyna** [comment]
I needed it to test auth service, so I'm working on it already

**Comment by suchov** [comment]
какой веселый монолог )))

**Comment by AMashoshyna** [comment]
@suchov че издеваешься, я тут новенькая))

**Comment by suchov** [comment]
@AMashoshyna так над новенькими же обычно и издеваются, не?

**Comment by AMashoshyna** [comment]
@suchov черт, логично
